### Use markdown formatting for the following questions (e.g., bold lettering, bullet points, different font sizes, etc.):


1. What does Pandas stand for?

Pandas stands for
* Panel Data
* Python Data Analysis

2. What are the 2 collections used in Pandas?
   * Series
   * DataFrame

3.  Name 4 things Pandas can do for us.
   * load
   * prepare
   * manipulate
   * analyselyze

4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
   
   Inplace is true

5. What is a CSV?

   comma separated values

6. When cleaning data what values do we not like in our data?
  * Duplicate values
  * Null values

### Please Complete this Coding Exercise:


7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()


In [81]:
import numpy as np
import pandas as pd
my_firstArray= np.arange(12).reshape(2, 3, 2)
my_firstArray

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20


In [82]:
Array = np.linspace(0, 20, num=6)
print("my array is =", Array)

my array is = [ 0.  4.  8. 12. 16. 20.]


9. Make a Deep Copy of the above array


In [83]:
import copy
Array1 = copy.deepcopy(Array)

print("The  deep copy Array is", Array1)

The  deep copy Array is [ 0.  4.  8. 12. 16. 20.]


10. Concatenate these 3 arrays into a new array named 'newArray'...

In [84]:
array1= ([[25, 16]])
array2= ([[11, 2], [13, 4]])
array3= ([[7, 81], [5, 6], [11, 12]])
newArray = np.concatenate((array1, array2, array3), axis=0)
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


11. Sort 'newArray' in order into 'sortedArray'



In [85]:
print(np.sort(newArray))

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


12. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.


In [86]:
m,n,p,q,r,s = newArray
print("m = ", m)
print("n = ", n)
print("p = ", p)
print("q = ", q)
print("r = ", r)
print("s = ", s)

m =  [25 16]
n =  [11  2]
p =  [13  4]
q =  [ 7 81]
r =  [5 6]
s =  [11 12]



13. Combined and sort the following arrays into one called 'comboArray' ...

In [87]:
one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array ([ 0, 1, 2, 3, 4, 5, 6, 7])
comboArray = np.concatenate((one, two,three),axis=0)
print('combined array is =', comboArray)
sorted_comboArray = np.sort(comboArray)
print('sorted comboArray in ascending order is=',sorted_comboArray)

combined array is = [10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
sorted comboArray in ascending order is= [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


14. Take 'comboArray' and perform the following slicing activities:


In [88]:
# print sec1 - the 2nd element
second_element=sorted_comboArray[1]
print('2nd element is=',second_element)

2nd element is= 1


In [89]:
#print sec2 - all elements from the 3rd element to the last
element3_last=sorted_comboArray[2:]
print('all element from 3 to the last =',element3_last)

all element from 3 to the last = [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [90]:
#print sec3 - all elements from the 4th to the 14th elements
element4_14=sorted_comboArray[3:15]
print('all element from 4 to the 14th =',element4_14)

all element from 4 to the 14th = [ 3  4  5  6  7 10 11 12 13 14 15 16]


In [91]:
#print sec4 - the last 6 elements
last_6=sorted_comboArray[18:]
print('the last 6 =',last_6)

the last 6 = [22 23 24 25 26 27]


In [92]:
#print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
zero_to_15 = sorted_comboArray[0:14]
print('all element from 0 to 15 inclusive =',zero_to_15)

all element from 0 to 15 inclusive = [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]


In [93]:
#print sec6 - from #20 every even element to the end
even_numbers = sorted_comboArray[sorted_comboArray % 2 == 0]
print('even numbers =',even_numbers)
# printing the even element from 20 to the end
print('even numbers from 20 =', even_numbers[8:])

even numbers = [ 0  2  4  6 10 12 14 16 20 22 24 26]
even numbers from 20 = [20 22 24 26]


In [94]:
#print sec7 - from the last element moving forward, every 5th element.

15. Using Series, create a DataFrame that looks like this:

In [95]:
my_DF = {
    "Ingredients": ["Flour", "Milk", "Eggs", "Spam"],
    "Quantity": [4,1,2,1],
    "Unit": ["cups", "cup", "large", "can"]
    }
my_DataFrame = pd.DataFrame(my_DF, columns=['Ingredients','Quantity', 'Unit'])
my_DataFrame

Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

In [96]:
my_DataFrame.set_index('Ingredients')

Quantity   Unit
Ingredients                 
Flour               4   cups
Milk                1    cup
Eggs                2  large
Spam                1    can

16. Take this data and create a DataFrame named studentData

In [97]:
   my_list= {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'Address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}
studentData = pd.DataFrame(my_list, columns=['Name', 'Height',
                                    'Qualification', 'Address','Age',
                                     'Pets', 'Sport'])
studentData

Name  Height Qualification  Address  Age        Pets           Sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

17. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]


In [98]:
deserts= ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData['Deserts']=deserts
studentData

Name  Height Qualification  Address  Age        Pets           Sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa

18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"


In [99]:
studentData.sort_values(by = ['Name','Address'], inplace = True)
studentData

Name  Height Qualification  Address  Age        Pets           Sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge


19. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

In [100]:
creating_CSV = studentData.to_csv('cows_and_goats.csv', index=False)

# checking the csv file
trying = pd.read_csv('cows_and_goats.csv')
trying

Name  Height Qualification  Address  Age        Pets           Sport  \
0     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
1   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
2      Jai     5.1           Msc    Delhi   21         Dog           Darts   
3  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Deserts  
0  Carrot Halwa  
1       waffels  
2     ice cream  
3  Cashew Fudge

20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it.


In [101]:
   my_list2= {'Bulbs': ['Ramp', 'Shallot', 'Onions', 'Garlic', 'Kurat', 'Leek'],
        'Flowers': ['Cauliflower','Broccoli', 'Cabbage', 'Dandelion', 'Voilets', 'Nasturtium'],
        'Leaves': ['Kale', 'Lettuce', 'Spinach', 'Collard', 'Parsley', 'Mint Leaves'],
        'Stems': ['Asparagus', 'Bamboo Shoots', 'Rhubard', 'Celery', 'Kohlrabi', 'Leaks', ],
        'Root & Tubers': ['Carrots', 'Beets','Potatoes', 'Taro', 'Parsnips', 'Radishes' ],
        'Fruits': ['Tomatoes', 'Cucumbers', 'Avocado', 'Olives', 'Eggplant','Sweet Corn']}
my_ownDF = pd.DataFrame(my_list2, columns=['Bulbs', 'Flowers',
                                    'Leaves', 'Stems','Root & Tubers', 'Fruits'])
my_ownDF

Bulbs      Flowers       Leaves          Stems Root & Tubers      Fruits
0     Ramp  Cauliflower         Kale      Asparagus       Carrots    Tomatoes
1  Shallot     Broccoli      Lettuce  Bamboo Shoots         Beets   Cucumbers
2   Onions      Cabbage      Spinach        Rhubard      Potatoes     Avocado
3   Garlic    Dandelion      Collard         Celery          Taro      Olives
4    Kurat      Voilets      Parsley       Kohlrabi      Parsnips    Eggplant
5     Leek   Nasturtium  Mint Leaves          Leaks      Radishes  Sweet Corn

In [102]:
creating_CSV2 = my_ownDF.to_csv('myown.csv', index=False)

# checking the csv file
tried = pd.read_csv('myown.csv')
tried

Bulbs      Flowers       Leaves          Stems Root & Tubers      Fruits
0     Ramp  Cauliflower         Kale      Asparagus       Carrots    Tomatoes
1  Shallot     Broccoli      Lettuce  Bamboo Shoots         Beets   Cucumbers
2   Onions      Cabbage      Spinach        Rhubard      Potatoes     Avocado
3   Garlic    Dandelion      Collard         Celery          Taro      Olives
4    Kurat      Voilets      Parsley       Kohlrabi      Parsnips    Eggplant
5     Leek   Nasturtium  Mint Leaves          Leaks      Radishes  Sweet Corn

   
   20.(B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

In [103]:
my_ownDF.to_csv('myown.csvi', sep='|',index=False)

In [104]:
tried1 = pd.read_csv('myown.csvi')
tried1

Bulbs|Flowers|Leaves|Stems|Root & Tubers|Fruits
0   Ramp|Cauliflower|Kale|Asparagus|Carrots|Tomatoes
1  Shallot|Broccoli|Lettuce|Bamboo Shoots|Beets|C...
2    Onions|Cabbage|Spinach|Rhubard|Potatoes|Avocado
3        Garlic|Dandelion|Collard|Celery|Taro|Olives
4   Kurat|Voilets|Parsley|Kohlrabi|Parsnips|Eggplant
5  Leek|Nasturtium|Mint Leaves|Leaks|Radishes|Swe...